<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Crane" name="Team2Test" tests="17" failures="3" timestamp="3 Jan 2019 12:39:12 GMT" time="1447.022" errors="0">
  <testcase name="TestReceivableApproveNoPass" time="92.276" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestReceivableApproveNoPassBath" time="83.157" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestReceivableApproveNoPassDelete" time="117.483" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestReceivableApproveNoPassModify" time="135.117" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestReceivableApprovePass" time="100.198" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestReceivableApprovePassBath" time="86.0" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestReceivableIssueModifyDelete" time="45.79" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestPayrollCreditApplySearchFinancingTabPage" time="122.655" classname="com.jxrt.test.Team2Test">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;[6]笔&amp;gt; but was:&amp;lt;[1]笔&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[6]笔> but was:<[1]笔>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at com.jxrt.biz.page.PayrollCreditApplySearchFinancingTabPage.payrollCreditFinancingList(PayrollCreditApplySearchFinancingTabPage.java:213)
	at com.jxrt.test.Team2Test.TestPayrollCreditApplySearchFinancingTabPage(Team2Test.java:1590)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestPayrollCreditApplySearchFinancingTabPage -->
  <testcase name="TestPayrollCreditApplySearchIssuingTabPage" time="127.818" classname="com.jxrt.test.Team2Test">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 100, Size: 93">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 100, Size: 93
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.jxrt.biz.page.PayrollCreditApplySearchIssuingTabPage.payrollCreditIssuingList(PayrollCreditApplySearchIssuingTabPage.java:191)
	at com.jxrt.test.Team2Test.TestPayrollCreditApplySearchIssuingTabPage(Team2Test.java:1512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestPayrollCreditApplySearchIssuingTabPage -->
  <testcase name="TestPayrollCreditApplySearchPage" time="238.21" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestRedeemNotice1208SendEmailBatch" time="24.007" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestRedeemNotice1208SendEmailCredit" time="23.598" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestRedeemNotice1208SendEmailReceivable" time="23.806" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestRedeemNotice206SendEmailCredit" time="25.647" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestRedeemNotice206SendEmailReceivable" time="24.618" classname="com.jxrt.test.Team2Test"/>
  <testcase name="TestRedeemNoticeCreditList" time="14.82" classname="com.jxrt.test.Team2Test">
    <failure type="junit.framework.ComparisonFailure" message="expected:&amp;lt;[0].00&amp;gt; but was:&amp;lt;[22].00&amp;gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<[0].00> but was:<[22].00>
	at junit.framework.Assert.assertEquals(Assert.java:85)
	at junit.framework.Assert.assertEquals(Assert.java:91)
	at com.jxrt.biz.page.RedeemNoticePage.redeemNoticeCreditList(RedeemNoticePage.java:236)
	at com.jxrt.test.Team2Test.TestRedeemNoticeCreditList(Team2Test.java:1009)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TestRedeemNoticeCreditList -->
  <testcase name="TestRedeemNoticeCreditNum" time="71.922" classname="com.jxrt.test.Team2Test"/>
</testsuite> <!-- Team2Test -->
